version: '2.1'
services:
  app:
    build: ./src
    links:
      - grafana_graphite
    environment:
      - ENDPOINT=grafana_graphite
      # - COMPlus_GCHeapCount=2 # Good throughput
      # - COMPlus_GCNoAffinitize=1 # Bad throughput
      # - COREHOST_TRACE=1
    ports:
      - '8000:8000'
    mem_limit: 104857600
    mem_reservation: 100m

  grafana_graphite:
    image: kamon/grafana_graphite
    container_name: kamon-grafana-dashboard
    ports:
      - '80:80'
      - '81:81'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
      - ./log/supervisor:/var/log/supervisor